In [1]:
import numpy as np

In [3]:
b=np.array([[-3,-2,-1],[0,2,-2],[-4,3,-3]])

In [4]:
 b.shape

(3, 3)

In [7]:
print(b[1,:])
print(b[:,1])

[ 0  2 -2]
[-2  2  3]


In [8]:
b[b>0]

array([2, 3])

In [9]:
 b[2]>0

array([False,  True, False])

In [10]:
b[:,2]>0

array([False, False, False])

In [11]:
   import math as m

In [13]:
b[1]=m.fabs(b[1])

TypeError: only size-1 arrays can be converted to Python scalars

In [17]:
m.fabs([-23])

TypeError: must be real number, not list

In [18]:
m.fabs(-2)

2.0

In [19]:
print(b)
b[1]=np.abs(b[1])
print(b)

[[-3 -2 -1]
 [ 0  2 -2]
 [-4  3 -3]]
[[-3 -2 -1]
 [ 0  2  2]
 [-4  3 -3]]


In [20]:
np.sum(b)

-6

In [22]:
print(b)
print(np.sum(b,axis=0))
print(np.sum(b,axis=1))

[[-3 -2 -1]
 [ 0  2  2]
 [-4  3 -3]]
[-7  3 -2]
[-6  4 -4]


In [23]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [24]:
np.arange(2,8)

array([2, 3, 4, 5, 6, 7])

In [25]:
np.linspace(start=2,stop=10,num=15)

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

In [26]:
 np.random.randint(high=10,low=1,size=(2,3))

array([[2, 6, 8],
       [6, 6, 6]])

In [27]:
 np.random.random(size=(2,3))

array([[0.43471673, 0.17297242, 0.72409518],
       [0.59810398, 0.7835982 , 0.99646088]])

In [32]:
x=np.arange(10)
y=np.random.choice(x,5)

In [33]:
np.random.choice(x,5,replace=False)

array([4, 8, 3, 2, 5])

In [35]:
print(y)
np.unique(y,return_counts=True)

[8 9 9 2 3]


(array([2, 3, 8, 9]), array([1, 1, 1, 2], dtype=int64))

In [36]:
x1=np.random.randint(high=100,low=2,size=(15,))
print(x1)

[ 4  2 20 52 31 47 33 96  2 37 70 48  5 78 41]


In [38]:
x1.sort()
print(x1)

[ 2  2  4  5 20 31 33 37 41 47 48 52 70 78 96]


In [39]:
x2=np.random.randint(high=100,low=2,size=(4,6))
x2

array([[ 4,  4, 13, 44, 24,  7],
       [61, 10, 32, 43, 61, 13],
       [17, 21, 67, 56, 22, 77],
       [22, 50, 48, 16,  3, 47]])

In [41]:
x2.sort()
print(x2)

[[ 4  4  7 13 24 44]
 [10 13 32 43 61 61]
 [17 21 22 56 67 77]
 [ 3 16 22 47 48 50]]


In [45]:
x3=np.random.randint(high=10,low=4,size=(5,))
x3

array([5, 4, 6, 9, 9])

In [48]:
x3.argsort() # return indices in thier respective sorted order 
# print(x3)

array([1, 0, 2, 3, 4], dtype=int64)

In [49]:
x.max()

9

In [50]:
x.argmax()

9